apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  application.properties: |
    server.port=8085
    testUser.name=scoobyDoo
    testUser.age=26
    testUser.pin=400089
    logging.level.org.springframework.web=DEBUG